exports.LOAD_CURRENT_GROUPS = 'LOAD_CURRENT_CONTACTS'; 
exports.LOAD_CURRENT_GROUP = 'LOAD_CURRENT_CHAT'; 
exports.SET_ONLINE_USERS = 'SET_ONLINE_USERS'; 



exports.UPDATE_CHAT_INFO = 'UPDATE_CHAT_INFO'; 
exports.SET_RECEIVER_DETAILS = 'SET_RECEIVER_DETAILS'; 


exports.UPDATE_GROUP_CHAT = 'UPDATE_CURRENT_CHAT'; 