exports.LOAD_CURRENT_CONTACTS = 'LOAD_CURRENT_CONTACTS'; 
exports.LOAD_CURRENT_CHAT = 'LOAD_CURRENT_CHAT'; 
exports.SET_ONLINE_USERS = 'SET_ONLINE_USERS'; 
exports.UPDATE_CHAT_INFO = 'UPDATE_CHAT_INFO'; 
exports.SET_RECEIVER_DETAILS = 'SET_RECEIVER_DETAILS'; 
exports.UPDATE_CURRENT_CHAT = 'UPDATE_CURRENT_CHAT'; 